### ISSUE TITLE
Alphabetical ordering of I/O binary files leads to Paraview visualization issue

### ISSUE THREAD

**Issue by bahardy** [CaNS-World/CaNS#126]
Care should be taken when one chooses names for the binary files in the I/O files (`out2d.90`,`out3d.h90`). 

The python script `write_xdmf.py` orders fields to be visualized in the `xdmf` file based on the name of the binary files. If the 3 components of a vector field (e.g. velocity) are not contiguous in terms of alphabetical ordering, `xdmf` will not  recognize it as a vector field but instead as 3 independent scalar fields, with annoying consequences in further Paraview visualization. 

As an example if 2-D slices binary files for the three velocity components are named as 
`u_slice_fld_*****.bin`, `v_slice_fld_*****.bin`, `w_slice_fld_*****.bin` 
and that, at the same time, we print vorticity components as 
`vox_slice_fld_*****.bin`, `voy_slice_fld_*****.bin`,`voz_slice_fld_*****.bin`, 
the three vorticity files will be printed in between `v_slice_fld_*****.bin` and `w_slice_fld_*****.bin`  in the `xdmf` file, so that the 3 velocity components will be considered as 3 distinct scalar fields.

**Comment by p-costa** [comment]
Good catch. This needs to be fixed. Again, thanks a lot for finding and reporting it!

The workaround for now is to name the output binary files such that, when all files are ordered alphabetically, three vector field components always appear consecutively in the list.

**Comment by p-costa** [comment]
Does changing the line in `write_xdmf` from:

`saves = np.sort(saves, order='isave')`

to

`saves = np.sort(saves, order=['isave', 'variable'])`

fix the issue?

**Comment by bahardy** [comment]
This fix seems to work perfectly ! :+1:

**Comment by p-costa** [comment]
Great! Thanks for checking!
