### ISSUE TITLE
Output suggestion.

### ISSUE THREAD

**Issue by soaringxmc** [CaNS-World/CaNS#127]
Hi, Pedro! I wold suggest to replace if(mod(istep,iout1d) == 0)  by if(iout1d > 0.and.mod(istep,iout1d) == 0), and also for iout0d, 2d, 3d, save. When no output is needed, we can just set iout1d=0 in input.nml. This should be more user-freindly than setting very large numbers for no output.

**Comment by p-costa** [comment]
Hi Mao,

Great idea! Would you like to submit a PR? Else, I can do it next week.

**Comment by soaringxmc** [comment]
Sure!

**Comment by p-costa** [comment]
Thanks Mao for your contribution!
